### PR TITLE
The Big BG Dump.

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a bunch of backgrounds to the new "abstract/" directory under /builtin. 
Right now, we have 12 "sets". Each set contains a light and dark variant of the given background in a 4k (3840x2160) Webp image, as well as a .svg/ that ships the vector source used to generate said images. 

I hope this a good start, and I figured I'd publish this sooner than later -- but in the future I definitely want to support color variants (so at minimum think the colors listed in the "Appearance" section of the Fyne Settings). I'm very excited by the idea Andy mentioned in the Discord, of moving them to grayscale and basically colorizing the bitmap to get this desired effect. Think we could effectively half the space these currently take (by maybe not even needing a light and dark variant). 

But in the short-term, we probably need to add a way to render Webp resources in Fynedesk proper. lol

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
Not sure about naming - the hidden directories are strange, why would you want that?
Also as a collection of backgrounds I would have thought "abstract" made more sense than "builtin/abstract"?

**Comment by andydotxyz** [comment]
This is a really epic collection, thanks so much for the contribution

**Comment by ghost** [comment]
> Not sure about naming - the hidden directories are strange, why would you want that? Also as a collection of backgrounds

The hidden directory criticism is fair, and it's something I was (and still am) about 50/50 on.  I'm completely fine with going with `svg/` proper. Though the line-of-reasoning was, I wanted to hide the "source" format from anything potentially user-facing... but yeah, this is probably naive in the fist-place and is maybe just more of a hassle than it's worth because there's a real chance of not knowing this is even there as a contributor. So, I'll at minimum make a new commit for that.

>  I would have thought "abstract" made more sense than "builtin/abstract"?

On this one, I think I'm just uninformed what `builtin` means in the given context.
I assumed builtin meant 'shipped' officially, and the main.go in there -- it was just setting the default. If this is "just" the `default` 'set' , maybe it's worth naming it that? Either-or, I'm also good with moving `abstract` up a level to the top-level -- as my initial commit seemed to imply it was anyways. lol

**Comment by ghost** [comment]
Also fyi, just updated the builtin's assets to include the new better justified / centered PNGs. Think I did it right. lol

edit: Also side-by-side I changed the colors a tiny bit more than I thought I did initially. :^)

**Review by andydotxyz — APPROVED** [review]
Nice one thanks :)

**Pull request merged**
